version: "3.7"
services:
  mongodb:
    # Сервис MongoDB
    image: mongo:latest # Используем образ MongoDB
    restart: always # Всегда перезапускать контейнер в случае ошибки
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Имя пользователя по умолчанию
      MONGO_INITDB_ROOT_PASSWORD: rootpassword # Пароль пользователя по умолчанию
      MONGODB_DATABASE: house
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "5521193243:AAG7UVUECV3E_vyk_rEirDOJRpbJ-I7EU7c"

    ports:
      - 127.0.0.1:27020:27020 # Проброс порта: локальный порт:27020 -> порт в контейнере:27020
    volumes:
      - mongodb_data:/data/db # Монтируем том для хранения данных MongoDB
  evo_telebot:
    # Сервис evo_telebot
    platform: linux/amd64
    build: . # Сборка контейнера из текущего каталога
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: house
      MONGODB_HOSTNAME: mongodb
      TELEGRAM_TOKEN: "5521193243:AAG7UVUECV3E_vyk_rEirDOJRpbJ-I7EU7c"

    volumes:
      - ./app:/home/nonroot/app # Монтирование кода приложения в контейнер
    #    volumes:
    #      - ./:/app
    command: sh -c "poetry run python3 bot/__init__.py" # Команда для запуска бота

    depends_on:
      - mongodb # Зависимость: ждем, пока MongoDB будет доступна

volumes:
  mongodb_data: # Том для MongoDB, используется для сохранения данных
